# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170421_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hours',
            field=models.ManyToManyField(blank=True, to='course.Hour'),
        ),
    ]
