# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170421_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
