# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170421_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hours',
            field=models.ManyToManyField(to='course.Hour'),
        ),
    ]
