# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studentprofile_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_query_name='teachers', to='course.Course'),
        ),
    ]
