# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0002_auto_20170421_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='users.TeacherProfile'),
        ),
    ]
