# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.TextField(default='DERP'),
            preserve_default=False,
        ),
    ]
