# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0003_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='users.StudentProfile'),
        ),
    ]
