# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hour',
            name='name',
            field=models.TextField(default='YEET'),
            preserve_default=False,
        ),
    ]
