# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20170421_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.TextField(default='HI'),
            preserve_default=False,
        ),
    ]
