# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_period_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='course',
            new_name='courses',
        ),
    ]
