# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170422_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
