# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_assignmentsubmission_is_graded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='is_graded',
            new_name='graded',
        ),
    ]
