# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20170422_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
