# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_assignmentsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_by',
            field=models.DateField(default='2017-5-6'),
            preserve_default=False,
        ),
    ]
