# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_assignment_due_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='comments',
            field=models.TextField(default='YEET'),
            preserve_default=False,
        ),
    ]
