# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_course_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingscale',
            name='course',
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.DeleteModel(
            name='GradingScale',
        ),
    ]
