# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20170430_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingcategory',
            name='name',
            field=models.TextField(default='HI', max_length=50),
            preserve_default=False,
        ),
    ]
