# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_gradingcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='course.Course'),
        ),
    ]
