# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20170506_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Term'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Term'),
            preserve_default=False,
        ),
    ]
